### ISSUE TITLE
Improve event hash when creating an execution

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/js-sdk#137]
The event hash is currently hardcoded and should be generated.

https://github.com/mesg-foundation/js-sdk/blob/master/packages/cli/src/commands/service/execute.ts#L66

**Comment by Roms1383** [comment]
Which way do you want to generate it?
Hash of the repository files?

**Comment by antho1404** [comment]
Issue migrated to liteflow-labs/liteflow-js#17
