### ISSUE TITLE
Daemon logs hang after around 40,000 lines

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/js-sdk#139]
When running `daemon:logs` on an engine that is running for around 2,000 blocks, the commands hangs and doesn't display new logs.
This issue is also occurring when running `docker service logs engine` so this is not an issue from the CLI.

The current workaround is to set a maximum number of lines to fetch using the `--tail`  flag:
```
mesg-cli daemon:logs --tail 10000
```

The fix seems to be already merged on docker repository but not release yet:
https://github.com/moby/moby/pull/39360

Let's close this issue when the linked docker PR is released.

**Comment by antho1404** [comment]
As a workaround, we could use the logs from the container and not the docker service that seems to be working correctly.
