### ISSUE TITLE
remove temp folder after downloading source code

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/js-sdk#14]
The cli should remove the folder containing the downloading service sources.

**Comment by antho1404** [comment]
This happens when we deploy from an URL. We are creating a temporary directory in the deployer file https://github.com/mesg-foundation/js-sdk/blob/master/packages/cli/src/utils/deployer.ts that should be removed.

**Comment by antho1404** [comment]
Issue migrated to liteflow-labs/liteflow-js#5
