### ISSUE TITLE
Expose tendermint port

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/js-sdk#159]
In order to access some Tendermint features eg: blocks, txs, validators, etc... we should be able to communicate with its API and so expose the RPC port of Tendermint when we start the daemon.

Default port: `26657`

**Comment by NicolasMahe** [comment]
@antho1404 should we close this issue as well?

**Comment by antho1404** [comment]
Closing based on this comment https://github.com/mesg-foundation/js-sdk/pull/160#issuecomment-573502587
