### ISSUE TITLE
Update generated doc when using service:doc command

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/js-sdk#174]
We need to update generated doc when using `service:doc` command, it is still directing to the marketplace:

```
### Deploy the Service

To deploy this service, go to [this service page](https://marketplace.mesg.com/services/{{sid}}) on the [MESG Marketplace](https://marketplace.mesg.com) and click the button "get/buy this service".
```

We need to replace it with the right commands!

Source file:
https://github.com/mesg-foundation/js-sdk/blob/master/packages/cli/assets/doc.md#deploy-the-service

**Comment by NicolasMahe** [comment]
Also need to update the README of the services on guthub

**Comment by antho1404** [comment]
fixed by https://github.com/mesg-foundation/js-sdk/pull/237
