### ISSUE TITLE
Simulate transaction before broadcasting

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/js-sdk#185]
Right now the transaction is sent with no simulation. This means that there is no fee optimization and no checks before sending it. We should add this step of simulating the transaction and adjusting the fees based on the simulation.

**Comment by NicolasMahe** [comment]
Could you quickly increase the hardcoded gas to much more?
Or put a flag / config to override it?
The service-ethereum cannot be deployed with the current gas limit:
```
➜  js-sdk git:(feature/task-refactoring) ✗ ./packages/cli/bin/run service:dev ../services/service-ethereum
  ✔ Starting environment
  ✔ Compiling service
  ✖ Creating service
    → out of gas: out of gas in location: WritePerByte; gasWanted: 300000, gasUsed: 349145
    Starting service
    Fetching service's logs
Error: out of gas: out of gas in location: WritePerByte; gasWanted: 300000, gasUsed: 349145
    at API.<anonymous> (~/Development/MESG/js-sdk/packages/api/lib/lcd.js:58:23)
    at Generator.next (<anonymous>)
    at fulfilled (~/Development/MESG/js-sdk/packages/api/lib/lcd.js:5:58)
```

**Comment by antho1404** [comment]
Issue migrated to liteflow-labs/liteflow-js#67
