### ISSUE TITLE
Improve publish resources to testnet

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/js-sdk#192]
Developers should not have to sync the whole network to be able to publish resources to the testnet

- [x] add login and logout commands (https://github.com/mesg-foundation/js-sdk/pull/193)
- [ ] add `deploy:service` and `deploy:process`

**Comment by antho1404** [comment]
The `deploy:process` command is a bit tricky. Right now I would like to separate entirely the dev environment and the "deploy" environment but the process relies on the deployment of services (in order to get the instance hash).

I see a few solutions to solve that:
- Compile the process and deploy all the services in the **dev environment** just to get the process definition and deploy it on the "production" environment
- Compile the process and deploy all the services directly on the "prod" environment (problem: in that case, the user will become a runner of the services used in the process)
- Only deploy definition of a process so the user will have to test it locally then get the definition and deploy it on the prod environment.
- Enforce the user to set an `instanceHash` in the process file, this way there is no service deployment/start (we can still keep this feature for the `process:dev`)

Any suggestions?

**Comment by NicolasMahe** [comment]
I will go with:
```
Enforce the user to set an instanceHash in the process file, this way there is no service deployment/start (we can still keep this feature for the process:dev)
```
but switch to:
```
Compile the process and deploy all the services directly on the "prod" environment (problem: in that case, the user will become a runner of the services used in the process)
```
when we have the publish/automatic start of runner on the network. And in the meantime, we can ask services' developer to contact us to deploy their service on the network?

**Comment by NicolasMahe** [comment]
@antho1404 let's try to implement it directly with a backend that manages the mnemonic and signs the tx.

**Comment by antho1404** [comment]
Issue migrated to liteflow-labs/liteflow-js#14
