### ISSUE TITLE
Update process compilation to add new filter functionalities

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/js-sdk#200]
Update process compilation to add new filter functionalities.
Linked with issue https://github.com/mesg-foundation/engine/issues/1734 and PRs:
- https://github.com/mesg-foundation/engine/pull/1737
- https://github.com/mesg-foundation/engine/pull/1738
- https://github.com/mesg-foundation/engine/pull/1739

Work to do

- [x] support of basic types for filters (string, bool, number) (https://github.com/mesg-foundation/js-sdk/pull/203)
- [x] new definition for the process yml to handle references (https://github.com/mesg-foundation/js-sdk/pull/205)
- [ ] support of complex types for filters (array, object) (https://github.com/mesg-foundation/js-sdk/issues/209)
- [ ] support any ancestor for references (stepKey / nodeKey) (https://github.com/mesg-foundation/js-sdk/issues/210)

**Comment by antho1404** [comment]
Issues created for the complex types (#209) and reference ancestors (#210).
These features are not a priority
