### ISSUE TITLE
Add tags for the generated content of the command gen-doc

### ISSUE THREAD

**Issue by romain-gsr** [mesg-foundation/js-sdk#21]
Command **gen-doc** is great but it overwrites any existing **README.md**.

Could you add surrounding tags for the generated content of the command gen-doc ?
This way the content can be seamlessly updated in a specific part of the README.

**Comment by Roms1383** [comment]
You should pick a unique delimiter that has to be set after header and optionally before footer, so that the **gen-doc** can write in-between.
Already did it before and it works.

**Comment by antho1404** [comment]
Something that could work is to use html comment.

`<!-- BEGIN_MESG_DOC -->`
`<!-- END_MESG_DOC -->`

Both delimiters would be optional and if not present, `BEGIN_MESG_DOC` will be line 0 of the file and `END_MESG_DOC` the latest line of the document.

Examples of how to use it:
```readme.md
## My title

whatever I want here

<!-- BEGIN_MESG_DOC -->
```

```readme.md
<!-- END_MESG_DOC -->

Create a custom footer here
```

and of course 

```readme.md
## My title

whatever I want here

<!-- BEGIN_MESG_DOC -->
<!-- END_MESG_DOC -->

Create a custom footer here
```

**Comment by antho1404** [comment]
Issue migrated to liteflow-labs/liteflow-js#7
