### ISSUE TITLE
Improve encoder by checking toJSON exist

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/js-sdk#25]
Let's not start to specify how to encode every special type.
The lib should check if the function `toJSON` is implemented and call it if it is. Otherwise, maybe simple call `JSON.stringify`?

Function to improve:
https://github.com/mesg-foundation/mesg-js/blob/d0844fde085d3b797f076a56152a867c7dc3ac4f/src/util/encoder.ts#L3-L30

_Originally posted by @NicolasMahe in https://github.com/mesg-foundation/mesg-js/pull/116/files#r309583299_

**Comment by antho1404** [comment]
Issue migrated to liteflow-labs/liteflow-js#66
