### ISSUE TITLE
Better CI and release process

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/js-sdk#26]
I released a version 4.2.1 with the CI and the version was published but without the sources.
The CI should be able to publish with the sources.

The workflow should be the following:
- Increase version (manually or with npm version)
- Create a tag with the version
- Push the tag on Github
- The CI test the sources
- The CI build the sources
- The CI publish the version with the build

After we push on the tags on git we shouldn't have any manual action to do

**Comment by Roms1383** [comment]
I can do it ^^
I already started on the related issue

**Comment by Roms1383** [comment]
My guess is there's 2 options here :

1. abide by commit messages convention and get everything automated (using for example `commitlint` and `semantic-release` libraries), but that implies that commit messages will have to be carefully written
1. get more flexibility but less automation by git tagging manually each release, have the CI to parse the tag name and deduct which files to upload to GitHub Release

As of the current state of the project by now I would recommend going for the second approach before considering full automation in the future.

**Comment by antho1404** [comment]
It seems that lerna has a command `lerna version` that creates and publishes the tags without publishing on npm. We could use that and then have a standard deploy on npm when there is a new tag. That would follow your second proposition.
Just something to keep in mind (even it shouldn't be a problem), we will have multiple packages in this repository so multiple tags for the different libraries. You can check the existing tags https://github.com/mesg-foundation/js-sdk/releases

**Comment by antho1404** [comment]
Issue migrated to liteflow-labs/liteflow-js#20
