### ISSUE TITLE
command daemon:logs should test is engine is running

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/js-sdk#5]
current output of `daemon:logs` when engine is not running is empty:

```bash
$ ./bin/run daemon:status         
Engine is... stopped
$ ./bin/run daemon:logs
```

**Comment by antho1404** [comment]
This is the current output when the engine is not running

```
➜  js-sdk git:(feature/yaml-validation) ✗ mesg-cli daemon:logs
 ›   Error: No engine is running.
```

It has been fixed already by @uivlis in https://github.com/mesg-foundation/js-sdk/pull/134 and released in [v0.1.2](https://www.npmjs.com/package/@mesg/cli)
