### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/js-sdk#56]
Make sure the documents are updated:
- [x] README on https://github.com/mesg-foundation/mesg-js
- [x] README on https://github.com/mesg-foundation/core
- [x] guide on https://docs.mesg.com
- [x] tuto on https://docs.mesg.com

**Comment by ilgooz** [comment]
We'll continue on this one after relevant PRs are merged, because implementation of public APIs still may change.

**Comment by antho1404** [comment]
I also suggest to remove all go example on the documentation
