### ISSUE TITLE
Create "wrapper" type for service

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/js-sdk#59]
We need to create new type for the wrapper function to use.
The generated type are not js developer friendly at all.

For example, https://github.com/mesg-foundation/mesg-js/pull/28/files#diff-ef7fcd1152991311bd36314bc5c76f17R24:
```js
listenTask({ ...tasks }: Tasks): ResponseStream<TaskData>
```
should not use TaskData from the generated pb files but use a JS friendly type like:
```ts
interface TaskData {	
     executionID: string	
     taskKey: string	
     inputData: string	
 }
```

---

We can actually keep the interface from https://github.com/mesg-foundation/mesg-js/blob/master/src/client/service-client.ts

**Comment by ilgooz** [comment]
> Please implement also the feedback from mesg-foundation/js-sdk#58.
> 
> Does passing tasks to `listenTask` call automatically the task when the service receive it?
> Does `listenTask` accept no argument and in this case, the developer has to use `stream.on('task',...`?
> 
> What is `grpc.ServiceError`? if it an error it doesn't need to be in the return type of the promise.

* Yes, we keep the previous behaviour as it's. Task handlers will be called when matching task execution is received.

* It's for errors. It'll be passed as an argument to the _catch()_ method when emitting event fails. In the next PRs, I'm planning to change _grpc.ServiceError_ type to plain _Error_ type. This way it'll not depend on the generated APIs. And, generated code for the web version is slightly different here (not _grpc.ServiceError_) so it's a good idea to change it as _Error_.
